name: Monitor Passport Website
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Still allows manual triggering
jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        id: check
        run: |
          URL=https://citaspasaporte.migraciones.gob.pe/citas-pasaporte-v2/
          echo "Checking $URL"
          curl -s -L --head "$URL"  # Debug output to logs
          if curl -s -L --head "$URL" | grep -E "^HTTP/[0-2]\.?[0-1]? 200( OK)?"; then
            echo "Site is up!"
            echo "SITE_UP=true" >> $GITHUB_OUTPUT
          else
            echo "Site is down!"
            echo "SITE_UP=false" >> $GITHUB_OUTPUT
          fi
      - name: Send notification if site is up
        if: steps.check.outputs.SITE_UP == 'true'
        run: |
          echo "The passport site is back online! Visit $URL to book your appointment."
          # Placeholder for notification; see Step 2