name: Monitor Passport Website
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Manual trigger for testing
jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        id: check
        run: |
          URL=https://citaspasaporte.migraciones.gob.pe/citas-pasaporte-v2/
          echo "Checking $URL"
          curl -s -L --head "$URL"
          if curl -s -L --head "$URL" | grep -E "^HTTP/[0-2]\.?[0-1]? 200( OK)?"; then
            echo "Site is up!"
            echo "SITE_UP=true" >> $GITHUB_OUTPUT
          else
            echo "Site is down!"
            echo "SITE_UP=false" >> $GITHUB_OUTPUT
          fi
      - name: Notify Discord if site is up
        if: steps.check.outputs.SITE_UP == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "Hey Cesar! <@memeai.> The passport site is back online! Visit https://citaspasaporte.migraciones.gob.pe/citas-pasaporte-v2/ now!"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
